# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('orderable_name', models.CharField(max_length=200)),
                ('orderable_code', models.CharField(max_length=200)),
                ('patient_id', models.IntegerField(default=0)),
                ('rpl_name', models.CharField(max_length=200)),
                ('rpl_code', models.CharField(max_length=200)),
                ('ordered_by', models.CharField(max_length=200)),
                ('supervised_by', models.CharField(max_length=200)),
                ('managed_by', models.CharField(max_length=200)),
                ('problem_ids', models.CharField(max_length=200)),
                ('req_number', models.CharField(max_length=200)),
                ('order_item_id', models.CharField(max_length=200)),
            ],
        ),
    ]
